version: "3.7"

services:
  web:
    build: .
    container_name: cavity.local.cvt.io
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:plout@db/cavity
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db.local.cvt.io
    environment:
      - POSTGRES_DB=cavity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=plout
