services:
  web:
    build: .
    container_name: cavity.njk.localhost
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cavity.rule=Host(`cavity.njk.localhost`)"
      - "traefik.http.routers.cavity.tls=true"
      - "traefik.docker.network=proxy"
    networks:
      - default
      - proxy
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - TOKEN_SECRET=mySuperSecret
      - SUPABASE_URL=http://172.17.0.1:54321
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SENDINBLUE_API_KEY=:D
      - DEVELOPMENT_MODE=1

networks:
  proxy:
    external: true
