version: "3.7"

services:
  node:
    build: .
    container_name: cavity.local.qks.io
    labels:
      - traefik.enable=true
      - traefik.http.routers.cavity.rule=Host(`cavity.local.qks.io`)
    networks:
      - proxy
    volumes:
      - .:/app

networks:
  proxy:
    external: true
