version: "3.7"

services:
  web:
    build: .
    container_name: cavity.njk.localhost
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cavity.rule=Host(`cavity.njk.localhost`)"
      - "traefik.http.routers.cavity.tls=true"
      - "traefik.docker.network=proxy"
    networks:
      - default
      - proxy
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres,plout,db,5432,cavity
      - TOKEN_SECRET=mySuperSecret
      - SENDINBLUE_API_KEY=:D
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db.njk.localhost
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      - POSTGRES_DB=cavity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=plout
      - PGDATA=/var/lib/postgresql/data/cavity
    volumes:
      - /var/lib/postgresql/data/cavity:/var/lib/postgresql/data/cavity
      - ./backup:/home

networks:
  proxy:
    external: true
