-- A lanncer sur supabase de prod pour ajouter les tables pour les tags
CREATE TABLE public.tag (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    name character varying NOT NULL
);

ALTER TABLE public.tag ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_account_id_id_key UNIQUE (account_id, id);

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT tag_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_tag_account_id ON public.tag(account_id);

-- Table tag_x_bottle
CREATE TABLE public.tag_x_bottle (
    _id integer NOT NULL,
    account_id integer NOT NULL,
    tag_id integer NOT NULL,
    bottle_id integer NOT NULL
);

ALTER TABLE public.tag_x_bottle ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_x_bottle__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tag_x_bottle
    ADD CONSTRAINT tag_x_bottle_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.tag_x_bottle
    ADD CONSTRAINT tag_x_bottle_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_tag_x_bottle_account_id ON public.tag_x_bottle(account_id);
CREATE INDEX IF NOT EXISTS idx_tag_x_bottle_tag_id ON public.tag_x_bottle(tag_id);
CREATE INDEX IF NOT EXISTS idx_tag_x_bottle_bottle_id ON public.tag_x_bottle(bottle_id);