--
-- Cavity Backend Database Schema (Clean - Production)
-- Extracted from Supabase, cleaned for local PostgreSQL use
--
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    registration_code integer,
    reset_token character varying(255),
    last_user character varying(255),
    last_update_time bigint
);

--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.account_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.account_id_seq OWNED BY public.account.id;

--
-- Name: bottle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bottle (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    wine_id integer NOT NULL,
    vintage integer NOT NULL,
    apogee integer,
    is_favorite integer NOT NULL,
    price real NOT NULL,
    currency character varying(255),
    other_info character varying(255) NOT NULL,
    buy_location character varying(255) NOT NULL,
    buy_date bigint NOT NULL,
    tasting_taste_comment character varying(255) NOT NULL,
    bottle_size character varying(255) NOT NULL,
    consumed integer NOT NULL,
    tasting_id integer,
    selected boolean DEFAULT false NOT NULL,
    pdf_path character varying(255) DEFAULT ''::character varying NOT NULL,
    alcohol double precision,
    storage_location text DEFAULT ''::text NOT NULL
);

--
-- Name: bottle__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bottle ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bottle__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: county; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.county (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    name character varying(255) NOT NULL,
    pref_order integer NOT NULL
);

--
-- Name: county__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.county ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.county__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: f_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.f_review (
    _id integer NOT NULL,
    account_id integer NOT NULL,
    bottle_id integer NOT NULL,
    review_id integer NOT NULL,
    value integer
);

--
-- Name: f_review_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.f_review ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.f_review_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: friend; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friend (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    name character varying(255),
    img_path character varying(255) DEFAULT ''::character varying NOT NULL
);

--
-- Name: friend__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.friend ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friend__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: grape; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grape (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    name character varying(255) NOT NULL
);

--
-- Name: grape__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grape ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grape__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: history_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.history_entry (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    date bigint NOT NULL,
    bottle_id integer NOT NULL,
    tasting_id integer,
    comment character NOT NULL,
    type integer,
    favorite integer
);

--
-- Name: history_entry__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.history_entry ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.history_entry__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: history_x_friend; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.history_x_friend (
    _id integer NOT NULL,
    account_id integer NOT NULL,
    history_entry_id integer NOT NULL,
    friend_id integer NOT NULL
);

--
-- Name: history_x_friend_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.history_x_friend ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.history_x_friend_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: q_grape; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.q_grape (
    _id integer NOT NULL,
    account_id integer NOT NULL,
    bottle_id integer NOT NULL,
    grape_id integer NOT NULL,
    percentage integer NOT NULL
);

--
-- Name: q_grape__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.q_grape ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.q_grape__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    contest_name character varying(255) NOT NULL,
    type integer NOT NULL
);

--
-- Name: review__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: tasting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasting (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    date bigint NOT NULL,
    is_midday boolean NOT NULL,
    opportunity character varying(255) NOT NULL,
    done boolean NOT NULL
);

--
-- Name: tasting__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tasting ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasting__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: tasting_action; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasting_action (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    type character varying(255),
    bottle_id integer NOT NULL,
    done integer
);

--
-- Name: tasting_action__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tasting_action ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasting_action__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: tasting_x_friend; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasting_x_friend (
    _id integer NOT NULL,
    account_id integer NOT NULL,
    tasting_id integer NOT NULL,
    friend_id integer NOT NULL
);

--
-- Name: tasting_x_friend_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tasting_x_friend ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasting_x_friend_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: wine; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wine (
    _id integer NOT NULL,
    id integer NOT NULL,
    account_id integer NOT NULL,
    name character varying(255) NOT NULL,
    naming character varying(255) NOT NULL,
    color character varying(255) NOT NULL,
    cuvee character varying(255) NOT NULL,
    is_organic integer NOT NULL,
    county_id integer NOT NULL,
    hidden integer NOT NULL,
    img_path character varying(255) DEFAULT ''::character varying NOT NULL
);

--
-- Name: wine__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wine ALTER COLUMN _id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wine__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: account id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account ALTER COLUMN id SET DEFAULT nextval('public.account_id_seq'::regclass);

--
-- Name: account account_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_email_key UNIQUE (email);

--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);

--
-- Name: bottle bottle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bottle
    ADD CONSTRAINT bottle_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.bottle
    ADD CONSTRAINT bottle_account_id_id_key UNIQUE (account_id, id);

--
-- Name: county county_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.county
    ADD CONSTRAINT county_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.county
    ADD CONSTRAINT county_account_id_id_key UNIQUE (account_id, id);

--
-- Name: f_review f_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.f_review
    ADD CONSTRAINT f_review_pkey PRIMARY KEY (_id);

--
-- Name: friend friend_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friend
    ADD CONSTRAINT friend_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.friend
    ADD CONSTRAINT friend_account_id_id_key UNIQUE (account_id, id);

--
-- Name: grape grape_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grape
    ADD CONSTRAINT grape_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.grape
    ADD CONSTRAINT grape_account_id_id_key UNIQUE (account_id, id);

--
-- Name: history_entry history_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_entry
    ADD CONSTRAINT history_entry_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.history_entry
    ADD CONSTRAINT history_entry_account_id_id_key UNIQUE (account_id, id);

--
-- Name: history_x_friend history_x_friend_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_x_friend
    ADD CONSTRAINT history_x_friend_pkey PRIMARY KEY (_id);

--
-- Name: q_grape q_grape_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_grape
    ADD CONSTRAINT q_grape_pkey PRIMARY KEY (_id);

--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_account_id_id_key UNIQUE (account_id, id);

--
-- Name: tasting_action tasting_action_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasting_action
    ADD CONSTRAINT tasting_action_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.tasting_action
    ADD CONSTRAINT tasting_action_account_id_id_key UNIQUE (account_id, id);

--
-- Name: tasting tasting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasting
    ADD CONSTRAINT tasting_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.tasting
    ADD CONSTRAINT tasting_account_id_id_key UNIQUE (account_id, id);

--
-- Name: tasting_x_friend tasting_x_friend_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasting_x_friend
    ADD CONSTRAINT tasting_x_friend_pkey PRIMARY KEY (_id);

--
-- Name: wine wine_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wine
    ADD CONSTRAINT wine_pkey PRIMARY KEY (_id);

ALTER TABLE ONLY public.wine
    ADD CONSTRAINT wine_account_id_id_key UNIQUE (account_id, id);

--
-- Name: bottle bottle_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bottle
    ADD CONSTRAINT bottle_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: county county_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.county
    ADD CONSTRAINT county_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: f_review f_review_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.f_review
    ADD CONSTRAINT f_review_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: friend friend_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friend
    ADD CONSTRAINT friend_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: grape grape_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grape
    ADD CONSTRAINT grape_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: history_entry history_entry_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_entry
    ADD CONSTRAINT history_entry_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: history_x_friend history_x_friend_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_x_friend
    ADD CONSTRAINT history_x_friend_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: q_grape q_grape_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.q_grape
    ADD CONSTRAINT q_grape_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: review review_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: tasting_action tasting_action_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasting_action
    ADD CONSTRAINT tasting_action_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: tasting tasting_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasting
    ADD CONSTRAINT tasting_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: tasting_x_friend tasting_x_friend_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasting_x_friend
    ADD CONSTRAINT tasting_x_friend_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Name: wine wine_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wine
    ADD CONSTRAINT wine_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

--
-- Create indexes for performance
--

CREATE INDEX IF NOT EXISTS idx_bottle_account_id ON public.bottle(account_id);
CREATE INDEX IF NOT EXISTS idx_bottle_wine_id ON public.bottle(wine_id);
CREATE INDEX IF NOT EXISTS idx_county_account_id ON public.county(account_id);
CREATE INDEX IF NOT EXISTS idx_f_review_account_id ON public.f_review(account_id);
CREATE INDEX IF NOT EXISTS idx_friend_account_id ON public.friend(account_id);
CREATE INDEX IF NOT EXISTS idx_grape_account_id ON public.grape(account_id);
CREATE INDEX IF NOT EXISTS idx_history_entry_account_id ON public.history_entry(account_id);
CREATE INDEX IF NOT EXISTS idx_history_x_friend_account_id ON public.history_x_friend(account_id);
CREATE INDEX IF NOT EXISTS idx_q_grape_account_id ON public.q_grape(account_id);
CREATE INDEX IF NOT EXISTS idx_review_account_id ON public.review(account_id);
CREATE INDEX IF NOT EXISTS idx_tasting_account_id ON public.tasting(account_id);
CREATE INDEX IF NOT EXISTS idx_tasting_action_account_id ON public.tasting_action(account_id);
CREATE INDEX IF NOT EXISTS idx_tasting_x_friend_account_id ON public.tasting_x_friend(account_id);
CREATE INDEX IF NOT EXISTS idx_wine_account_id ON public.wine(account_id);
